#!/usr/bin/env bash
set -euo pipefail

SERVER_URL="${1:-${HIDBRIDGE_SERVER_URL:-http://127.0.0.1:8080}}"
TOKEN="${2:-${HIDBRIDGE_TOKEN:-}}"
ROOM="${3:-${HIDBRIDGE_WEBRTC_ROOM:-video}}"
STUN="${4:-${HIDBRIDGE_STUN:-stun:stun.l.google.com:19302}}"

export HIDBRIDGE_SERVER_URL="$SERVER_URL"
export HIDBRIDGE_TOKEN="$TOKEN"
export HIDBRIDGE_WEBRTC_ROOM="$ROOM"
export HIDBRIDGE_STUN="$STUN"

echo "HIDBRIDGE_SERVER_URL=$HIDBRIDGE_SERVER_URL"
echo "HIDBRIDGE_WEBRTC_ROOM=$HIDBRIDGE_WEBRTC_ROOM"
echo "HIDBRIDGE_STUN=$HIDBRIDGE_STUN"

go run .

