#!/usr/bin/env bash
set -euo pipefail

SERVER_URL="${1:-${HIDBRIDGE_SERVER_URL:-http://127.0.0.1:8080}}"
TOKEN="${2:-${HIDBRIDGE_TOKEN:-}}"
ROOM="${3:-${HIDBRIDGE_WEBRTC_ROOM:-video}}"
STUN="${4:-${HIDBRIDGE_STUN:-stun:stun.l.google.com:19302}}"
SOURCE_MODE="${5:-${HIDBRIDGE_VIDEO_SOURCE_MODE:-testsrc}}"
QUALITY_PRESET="${6:-${HIDBRIDGE_VIDEO_QUALITY_PRESET:-balanced}}"
FFMPEG_ARGS="${7:-${HIDBRIDGE_VIDEO_FFMPEG_ARGS:-}}"
CAPTURE_INPUT="${8:-${HIDBRIDGE_VIDEO_CAPTURE_INPUT:-}}"

export HIDBRIDGE_SERVER_URL="$SERVER_URL"
export HIDBRIDGE_TOKEN="$TOKEN"
export HIDBRIDGE_WEBRTC_ROOM="$ROOM"
export HIDBRIDGE_STUN="$STUN"
export HIDBRIDGE_VIDEO_SOURCE_MODE="$SOURCE_MODE"
export HIDBRIDGE_VIDEO_QUALITY_PRESET="$QUALITY_PRESET"
if [ -n "${FFMPEG_ARGS}" ]; then export HIDBRIDGE_VIDEO_FFMPEG_ARGS="$FFMPEG_ARGS"; fi
if [ -n "${CAPTURE_INPUT}" ]; then export HIDBRIDGE_VIDEO_CAPTURE_INPUT="$CAPTURE_INPUT"; fi

echo "HIDBRIDGE_SERVER_URL=$HIDBRIDGE_SERVER_URL"
echo "HIDBRIDGE_WEBRTC_ROOM=$HIDBRIDGE_WEBRTC_ROOM"
echo "HIDBRIDGE_STUN=$HIDBRIDGE_STUN"
echo "HIDBRIDGE_VIDEO_SOURCE_MODE=$HIDBRIDGE_VIDEO_SOURCE_MODE"
echo "HIDBRIDGE_VIDEO_QUALITY_PRESET=$HIDBRIDGE_VIDEO_QUALITY_PRESET"

go run .
